KPMP-4530_fix-release-ver
KPMP/hydra-data pull request #2
Opened 2023-07-18 16:54 UTC by Dert1129

2023-07-18 20:10 UTC, rlreamy requested changes
See comments

2023-07-18 20:10 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryDatasetService.java
> +		String maxReleaseVersion = fileRepo.max();
Your indentation here is pretty wild...let's line this up so it doesn't look like it is in a conditional or something.

2023-07-18 20:10 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryDatasetService.java
> +    List <RepositoryDataset> datasets = new ArrayList<>();
This line and the next could be replaced with a simple
``List <RepositoryDataset> datasets = fileRepo.findAll();``

2023-07-18 20:10 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryFileDataset.java
> +    private String participantIdSort;
Let's keep all of our variables defined at the top of the class...having them interspersed in the file makes the code much less readable.

2023-07-18 20:10 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryFileDataset.java
> +        fileNameSort = fileName.substring(37, fileName.length());
Please make the number 37 a constant, and call it something like 'UUID_LENGTH'

2023-07-18 20:10 UTC, rlreamy commented on src/test/java/org/kpmp/repositoryDataset/RepositoryFileDatasetTest.java
> +    public void setFileNameSort() {
This should be named something more like 'getFileNameSort' since there is not set method named that.

2023-07-18 20:10 UTC, rlreamy commented on src/test/java/org/kpmp/repositoryDataset/RepositoryFileDatasetTest.java
> +    public void setParticipantIdSort(){
DItto with the name...'getParticipantSort'

2023-07-18 20:10 UTC, rlreamy commented on src/test/java/org/kpmp/repositoryDataset/RepositoryFileDatasetTest.java
> +    public void setPlatformSort() {
Ditto the name 'getPlatformSort'

2023-07-18 20:10 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryFileDataset.java
> +
Do we need to worry about a file with 0 participant ids?
Also, upon looking at the view this is working with, I don't think this is going to work the way you want. When I search for the clinical data file, I don't see comma separated participant ids, I see lots of entries for the same file. So, with the way this is written, we would have the clinical data file listed a million times.

2023-08-01 15:11 UTC, zwright commented on src/main/resources/knowledge_environment.graphqls
> +    doi: [String]
I thought this had to be changed to "dois"

2023-08-01 15:12 UTC, zwright commented on src/main/resources/knowledge_environment.graphqls
> +    dlFileId: String
I thought this had to be changed to "file_id"?

2023-08-03 17:23 UTC, zwright approved these changes

2023-08-07 18:48 UTC, rlreamy requested changes
see comments

2023-08-07 18:48 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryDatasetDisplay.java
We really should have tests on this. There is logic inside some of the getters/setters.

2023-08-07 18:48 UTC, rlreamy commented on src/main/java/org/kpmp/Query.java
Add a test

2023-08-07 18:48 UTC, rlreamy commented on src/main/java/org/kpmp/arFileInfo/ArFileInfo.java
Add tests. I know this is a simple POJO (plain old java object), but I would like us to have decent test coverage on our code so when we make changes we see failures when we mess up.

2023-08-07 18:48 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryDatasetService.java
> +                System.out.println("Adding redcapId " + repositoryDataset.getId().getRedcapId());
Let's get rid of the sysout, and this if statement...this looks like it was added for testing

2023-08-07 18:48 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryDatasetService.java
> +            if(repositoryDataset.getId().getDlFileId().equalsIgnoreCase("E283EACF-7950-4165-85E2-CE0128CDAA26")){
let's get rid of this debugging code.

2023-08-07 18:48 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryFileDatasetId.java
tests

2023-08-07 18:48 UTC, rlreamy commented on src/test/java/org/kpmp/repositoryDataset/RepositoryFileDatasetTest.java
> +    // @Test
We should not leave commented out tests. These should be updated to pass, or if the method has been removed, remove the code.

2023-08-07 18:48 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryFileDatasetRepository.java
> +    @Query (value = "SELECT release_version FROM ar_file_info", nativeQuery = true)
Is this method being used? It doesn't look like it. Let's remove it if it is not needed.

2023-08-07 18:48 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryFileDatasetRepository.java
> +    @Query (value = "SELECT MAX(release_version) AS max FROM ar_file_info", nativeQuery = true)
Is there a reason we aren't getting the max from the repo_file_v table?

2023-08-07 18:48 UTC, rlreamy commented on src/main/java/org/kpmp/arFileInfo/ArFileInfo.java
Actually, is this class used? If it is not used, let's trash it.

2023-08-08 14:49 UTC, rlreamy requested changes

2023-08-10 18:02 UTC, rlreamy requested changes

2023-08-10 18:02 UTC, rlreamy commented on src/test/java/org/kpmp/repositoryDataset/RepositoryDatasetDisplayTest.java
> +  public void setPlatformSort(){
Oopsies...you did not call set.

2023-08-11 14:54 UTC, rlreamy approved these changes

2023-08-11 14:54 UTC, rlreamy approved these changes

2023-08-11 14:54 UTC, merged