add clinical information with endpoint
KPMP/hydra-data pull request #41
Opened 2024-11-04 18:00 UTC by Dert1129

2024-11-04 18:59 UTC, rlreamy requested changes

2024-11-04 18:59 UTC, rlreamy commented on src/test/java/org/kpmp/QueryTest.java
> +        repositoryFileDataset.setenrollmentCategory("organic");
this should be setEnrollmentCategory (with a capital E)

2024-11-04 18:59 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryDatasetDisplay.java
> +        if (shouldAdd(repositoryFile.getenrollmentCategory())) {
getEnrollment with a cap E

2024-11-04 18:59 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryDatasetDisplay.java
> +    public void addenrollmentCategory(String enrollmentCategory) {
addEnrollment... with a cap E

2024-11-04 18:59 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryDatasetDisplay.java
Generally speaking we should be following Java naming conventions and have camelCase....that means the getters/setters/adders etc should be getEnrollment, not getenrollment.

This can actually be important when you are using Spring, because it looks for things based on the name of the method.

2024-11-04 18:59 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryDatasetService.java
Ditto the comment about Java naming standards above.

2024-11-04 18:59 UTC, rlreamy commented on src/main/java/org/kpmp/repositoryDataset/RepositoryFileDataset.java
Ditto.

2024-11-05 20:51 UTC, zwright approved these changes

2024-11-05 20:55 UTC, merged